### ISSUE TITLE
Running pip install -r requirements.txt throws up error

### ISSUE THREAD

**Issue by fomalhaut-b** [coldmanck/RVL-BERT#1]
Hi @coldmanck ,
After running pip install -r requirements.txt it's throwing up error saying "is it == instead of =". Changing this does not fix. Could you once check if there was any error?

**Comment by coldmanck** [comment]
Hi, thank you for your interest in our project! 

Sorry that the original `requirements.txt` file doesn't work. This project is constructed with Python 3.6, PyTorch 1.1.0, and CUDA 9.0 and is largely based on [VL-BERT](https://github.com/jackroos/VL-BERT). Please follow [the original instruction](https://github.com/jackroos/VL-BERT/tree/master#environment) to install a conda environment. I've also uploaded a new `requirements.txt` (basically the same as in VL-BERT) and updated the `README.MD` file.

**Comment by fomalhaut-b** [comment]
Hi, thanks. This worked. I wasn't able to run script since I dont have cuda, so i'll try it again on cuda. How to run your code on custom inputs? Is retraining code available? I think you are just using pretrained weights right?

**Comment by coldmanck** [comment]
Hi, we only provide inference scripts and trained checkpoints for evaluation purposes only, and yes, we incorporate visual-linguistic knowledge in the pretrained weights from VL-BERT.
